name: Build, Test and Deploy RUM Records
env: 
    ELASTIC_APM_AUTH_TOKEN: ${{ secrets.ELASTIC_APM_AUTH_TOKEN }}
    ELASTIC_DEPLOYMENT_URL: ${{ secrets.ELASTIC_DEPLOYMENT_URL }}
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm ci && npm run test
        working-directory: ./apps/rum-records-react
      - run: npm ci && npm run test
        working-directory: ./apps/record-store-server-node-js        