name: Build, Test and Deploy RUM Records
env: 
    ELASTIC_APM_AUTH_TOKEN: ${{ secrets.ELASTIC_APM_AUTH_TOKEN }}
    ELASTIC_DEPLOYMENT_URL: ${{ secrets.ELASTIC_DEPLOYMENT_URL }}
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx run-many --target=lint --projects=rum-records-react,record-store-server-node-js --parallel=2
      - run: npx nx run-many --target=test --projects=rum-records-react,record-store-server-node-js --parallel=2 --ci --code-coverage
      - run: npx nx serve record-store-server-node-js && npx nx e2e rum-records-react-e2e
      - run: npx nx run-many --target=build --projects=rum-records-react,record-store-server-node-js --parallel=2